###Crear un usuario
POST http://localhost:9999/users/register HTTP/1.1
Content-Type: application/json

{
   "_id":"noadmin",
   "name":"Alejandro",
   "surname":"Gonzalez",
   "email":"hola@UberRoutes.com",
   "password":"admin",
   "followers":[],
   "following":[],
   "picture" :"example-user.png",
   "web":"admin.com",
   "admin":false
}

###Obtener todos los usuarios
GET http://localhost:9999/users/ HTTP/1.1


###obtener solo un usuario
GET http://localhost:9999/users/NikCannotDie HTTP/1.1


###Update de usuario
PUT http://localhost:9999/users/NikCannotDie HTTP/1.1
Content-Type: application/json

{
   "_id":"NikCannotDie",
   "name":"Nikolai",
   "surname":"Belinski",
   "email":"nik@US.com",
   "password":"Nikolai",
   "followers":"ejemplo",
   "picture" :"ejemplo",
   "registro":"registro",
   "web":"webhttp"
}

###eliminar usuario
DELETE http://localhost:9999/users/DempseyTank3 HTTP/1.1


###sim login
POST http://localhost:9999/users/login HTTP/1.1
Content-Type: application/json

{
   "_id":"DempseyTank2",
   "password":"Dempsey"
}

###get posts
GET http://localhost:9999/posts HTTP/1.1

###get especifico
GET http://localhost:9999/posts/Ruta1 HTTP/1.1

###get de rutas por usuario
POST http://localhost:9999/posts/byuser HTTP/1.1
Content-Type: application/json

{
   "user":"admin"
}

###Crear un post
POST http://localhost:9999/posts/create HTTP/1.1
Content-Type: application/json

{
   "name":"Ruta de la montaña alpina",
   "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel magna sit amet purus molestie finibus in at enim. Phasellus elementum feugiat ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum mi ipsum, tristique luctus erat in, faucibus interdum nibh. Sed sit amet nulla a lectus vestibulum hendrerit nec eu elit. Nullam dapibus sem ex, quis placerat arcu cursus et. Ut odio turpis, semper ac felis nec, accumsan tempor nunc. Fusce mauris ante, consectetur vel fringilla vitae, rutrum id diam. Cras vitae nisi sollicitudin, vestibulum sem ut, hendrerit enim.",
   "category":"Ciclismo",
   "distance":"2Km",
   "difficulty":"hard",
   "duration":"3h",
   "privacy":"public",
   "user":"admin"
}

###Crear un post2
POST http://localhost:9999/posts/create HTTP/1.1
Content-Type: application/json

{
   "name":"Ruta de la senderismo por aqui y por alla es una prueba por si esto es muy largo",
   "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel magna sit amet purus molestie finibus in at enim. Phasellus elementum feugiat ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum mi ipsum, tristique luctus erat in, faucibus interdum nibh. Sed sit amet nulla a lectus vestibulum hendrerit nec eu elit. Nullam dapibus sem ex, quis placerat arcu cursus et. Ut odio turpis, semper ac felis nec, accumsan tempor nunc. Fusce mauris ante, consectetur vel fringilla vitae, rutrum id diam. Cras vitae nisi sollicitudin, vestibulum sem ut, hendrerit enim.",
   "category":"Senderismo",
   "distance":"5Km",
   "difficulty":"media",
   "duration":"1h",
   "privacy":"public",
   "user":"prueba1"
}

###Update de post
PUT http://localhost:9999/posts/Ruta1 HTTP/1.1
Content-Type: application/json

{
   "_id":"Ruta1",
   "description":"descripcion modificada",
   "category":"a pie",
   "distance":"10 Km",
   "difficulty":"dificil",
   "duration":"1 hora",
   "images":[],
   "privacy" :"publica",
   "user":"usuario",
   "url":"url"
}

###Update de post por admin
PUT http://localhost:9999/posts/admupdate/Rutadelamontañaalpina-14-02-2023-04:14:49 HTTP/1.1
Content-Type: application/json

{
   "name":"Ruta de la montaña alpina derrapante",   
   "category":"bici",
   "distance":"40 Km",
   "difficulty":"moderado"
}

###Update de user por admin
PUT http://localhost:9999/users/adm/adminejemplo HTTP/1.1
Content-Type: application/json

{
   "name":"adm que vende ford ka",   
   "surname":"jajaXD",
   "web":"jaja",
   "admin":true
}
   
###eliminar ruta
DELETE http://localhost:9999/posts/Ruta1 HTTP/1.1

###Get all comments
GET http://localhost:9999/comments/ HTTP/1.1
###Get single comment
GET http://localhost:9999/comments/Rutadelamontañaalpina-14-02-2023-08:32:01 HTTP/1.1


###Crear un comentario
POST http://localhost:9999/comments/ HTTP/1.1
Content-Type: application/json

{
   "description":"En esta ruta derrapas",
   "user":"admin",
   "post":"Rutadelamontañaalpina-14-02-2023-08:32:01"
}

###put que cambia description
PUT http://localhost:9999/comments/description/63ee76d7a5952c529e49b4ae HTTP/1.1
Content-Type: application/json

{
   "description":"En esta ruta pasa algo jajajaja",
   "user":"admin",
   "post":"Rutadelamontañaalpina-14-02-2023-08:32:01"
}

###Borrar ruta por id
DELETE http://localhost:9999/comments/63ee76d7a5952c529e49b4ae HTTP/1.1
Content-Type: application/json

{
   "user":"admin",
}