###Crear un usuario
POST http://localhost:9999/users/register HTTP/1.1
Content-Type: application/json

{
   "_id":"DempseyTask2",
   "name":"Dempsey",
   "surname":"Tank",
   "email":"Demp@USA.com",
   "password":"Dempsey",
   "followers":[],
   "following":[],
   "picture" :"example",
   "web":"httpJAJAJA"
}

###Obtener todos los usuarios
GET http://localhost:9999/users/ HTTP/1.1


###obtener solo un usuario
GET http://localhost:9999/users/NikCannotDie HTTP/1.1


###Update de usuario
PUT http://localhost:9999/users/NikCannotDie HTTP/1.1
Content-Type: application/json

{
   "_id":"NikCannotDie",
   "name":"Nikolai",
   "surname":"Belinski",
   "email":"nik@US.com",
   "password":"Nikolai",
   "followers":"ejemplo",
   "picture" :"ejemplo",
   "registro":"registro",
   "web":"webhttp"
}

###eliminar usuario
DELETE http://localhost:9999/users/DempseyTank3 HTTP/1.1


###sim login
POST http://localhost:9999/users/login HTTP/1.1
Content-Type: application/json

{
   "_id":"DempseyTank2",
   "password":"Dempsey"
}

###get posts
GET http://localhost:9999/posts HTTP/1.1

###get especifico
GET http://localhost:9999/posts/Ruta1 HTTP/1.1

###Crear un post
POST http://localhost:9999/posts/create HTTP/1.1
Content-Type: application/json

{
   "name":"Ruta nueva",
   "description":"descripcion",
   "category":"Ciclismo",
   "distance":"2Km",
   "difficulty":"hard",
   "duration":"3h",
   "privacy":"public",
   "user":"DempseyTank2"
}

###Update de post
PUT http://localhost:9999/posts/Ruta1 HTTP/1.1
Content-Type: application/json

{
   "_id":"Ruta1",
   "description":"descripcion modificada",
   "category":"a pie",
   "distance":"10 Km",
   "difficulty":"dificil",
   "duration":"1 hora",
   "images":[],
   "privacy" :"publica",
   "user":"usuario",
   "url":"url"
}
   
###eliminar usuario
DELETE http://localhost:9999/posts/Ruta1 HTTP/1.1

###Get image
GET http://localhost:9999/img/post/example-post.jpg HTTP/1.1