###Crear un usuario
POST http://localhost:9999/users/ HTTP/1.1
Content-Type: application/json

{
   "_id":"DempseyTank",
   "name":"Dempsey",
   "surname":"Tank",
   "email":"Demp@USA.com",
   "password":"Dempsey",
   "followers":"70",
   "picture" :"ejemplo",
   "registro":"registro",
   "web":"httpJAJAJA"
}

###Obtener todos los usuarios
GET http://localhost:9999/users/ HTTP/1.1


###obtener solo un usuario
GET http://localhost:9999/users/NikCannotDie HTTP/1.1


###Update de usuario
PUT http://localhost:9999/users/NikCannotDie HTTP/1.1
Content-Type: application/json

{
   "_id":"NikCannotDie",
   "name":"Nikolai",
   "surname":"Belinski",
   "email":"nik@US.com",
   "password":"Nikolai",
   "followers":"40",
   "picture" :"ejemplo",
   "registro":"registro",
   "web":"webhttp"
}

###eliminar usuario
DELETE http://localhost:9999/users/DempseyTank HTTP/1.1